version: "3.8"

services:
  nginx:
    image: nginx
    container_name: nginx_drupal
    expose:
      - "80"
    ports:
      - "80:80"
    volumes:
      - ./configurations/nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./apps/drupal:/var/www/html:rw
    links:
      - php-app
  php-app:
    build: ./configurations/docker
    container_name: php_drupal
    volumes:
      - ./apps/drupal:/var/www/html:rw
      - ./configurations/others/bash_aliases.txt:/root/.bash_aliases:rw
      - ./configurations/php/custom.ini:/user/local/etc/php/conf.d/custom.ini:ro
    privileged: true
    tty: true
    links:
      - database-app
  database-app:
    image: mysql:5.7
    container_name: mysql_drupal
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./configurations/mysql/config:/config
      - ./configurations/mysql/data:/var/lib/mysql
